### ISSUE TITLE
URN::parse panics on UTF strings

### ISSUE THREAD

**Issue by FrancisMurillo** [chayleaf/urn#3]
## Description

`URN::parse` panics when it tries to lowercase a UTF string. I am aware that the RFC specifies only ASCII characters but it should return `Err` instead. 

My current workaround is to check with `str::is_ascii` before parsing.

```rust
assert!("6򭞦*c!󈰠v #®􇣺[®nE⁐c;gPS5<5!¡r󠀁R⁎".parse::<Urn>().is_ok());
```

```shell
thread 'tests::custom_test' panicked at 'byte index 4 is not a char boundary; it is inside '\u{ad7a6}' (bytes 1..5) of `6򭞦*c!󈰠v #®􇣺[®nE⁐c;gPS5<5!¡r󠀁R⁎`', src/lib.rs:76:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by chayleaf** [comment]
thanks for the report, should be fixed in 0.5.1!
